services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: ecoride_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
      - ./flask_app/app/db_store/db_init.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  mongo:
    image: mongo:7.0.28
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      # for mongo init
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    volumes:
      - ./docker/mongo:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
  
  flask_ecoride:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: flask_ecoride
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./flask_app:/flask_app
    depends_on:
      - postgres
      - mongo
    command: "python main.py"

volumes:
  db:
  mongo_data:
